### ISSUE TITLE
Error when running CoTracker with cotracker2v1.pth in Colab

### ISSUE THREAD

**Issue by W-Nabe** [facebookresearch/co-tracker#105]
Thank you for the CoTracker version update.

I wanted to try it out, so I replaced cotracker2.pth with cotracker2v1.pth in Colab and ran the following command, but I got an error:

```
!python /content/co-tracker/online_demo.py --checkpoint /content/co-tracker/checkpoints/cotracker2v1.pth
```

Error:
```
/content/co-tracker/cotracker/models/build_cotracker.py:30: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(f, map_location="cpu")
Traceback (most recent call last):
  File "/content/co-tracker/online_demo.py", line 52, in <module>
    model = CoTrackerOnlinePredictor(checkpoint=args.checkpoint)
  File "/content/co-tracker/cotracker/predictor.py", line 188, in __init__
    model = build_cotracker(checkpoint, window_len=window_len)
  File "/content/co-tracker/cotracker/models/build_cotracker.py", line 33, in build_cotracker
    cotracker.load_state_dict(state_dict)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CoTracker2:
	size mismatch for time_emb: copying a param with shape torch.Size([1, 16, 456]) from checkpoint, the shape in current model is torch.Size([1, 8, 456]).
```

How can I resolve this issue?

**Comment by lxin98** [comment]
I also encountered this problem

**Comment by Zhoues** [comment]
Is there anything new? I also encountered this problem :(
