### ISSUE TITLE
TypeError when tracing model by TorchScript

### ISSUE THREAD

**Issue by 2484432566** [facebookresearch/co-tracker#98]
Hi, I was tring to trace cotracker2.pth by TorchScript and save model as cotracker2.pt, but encountered a TypeError.

The code is as followed.

```
import torch
from cotracker.predictor import CoTrackerPredictor

model = CoTrackerPredictor()
model.load_state_dict(torch.load('./checkpoints/cotracker2.pth'), strict=False)
model.eval()
x = torch.randn(1, 8, 3, 384, 512, device="cpu")

traced_script_module = torch.jit.trace(model, x)
traced_script_module.save('./checkpoints/cotracker2.pt')
```

Error:

```
Traceback (most recent call last):
  File "E:\AAA_Tracking\co-tracker-main_tc\demo.py", line 164, in <module>
    traced_script_module = torch.jit.trace(model, x)
  File "E:\Anaconda3\Anaconda3\envs\co-tracker-main_tc\lib\site-packages\torch\jit\_trace.py", line 798, in trace
    return trace_module(
  File "E:\Anaconda3\Anaconda3\envs\co-tracker-main_tc\lib\site-packages\torch\jit\_trace.py", line 1065, in trace_module
    module._c._create_method_from_trace(
  File "E:\Anaconda3\Anaconda3\envs\co-tracker-main_tc\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\Anaconda3\Anaconda3\envs\co-tracker-main_tc\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\Anaconda3\Anaconda3\envs\co-tracker-main_tc\lib\site-packages\torch\nn\modules\module.py", line 1508, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "E:\Anaconda3\Anaconda3\envs\co-tracker-main_tc\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
TypeError: forward() missing 1 required positional argument: 'queries'
```

Can anyone help me to solve this problem?:(

**Comment by nikitakaraevv** [comment]
Hi @2484432566, the model takes two tensors as input: a video, and query points that you want to track. In this example, you're passing only one argument. 

However, I'm not sure that fixing this problem will allow to trace the model because of the way it's currently implemented. We're not working on that right now, but I agree that it's an important problem.

**Comment by 2484432566** [comment]
Hi @nikitakaraevv , thanks for your reply. After tring some fix like this, the code can run successfully: 
```
import torch
from cotracker.predictor import CoTrackerPredictor

model = CoTrackerPredictor()
model.to("cuda")
model.load_state_dict(torch.load('./checkpoints/cotracker2.pth'), strict=False)
model.eval()
x = torch.randn(1, 30, 3, 384, 512, device="cuda")
y = torch.randn(1, 304, 3, device="cuda")

# traced_script_module = torch.jit.trace(model, x)
traced_script_module = torch.jit.trace(model, (x, y))
traced_script_module.save('./checkpoints/cotracker2.pt')
```
Now it can generate .pt file for further research. Thanks again.
